RDSS-807
JiscRDSS/taxonomyschema pull request #1
Opened 2017-04-28 11:51 UTC by techjacker

Taxonomy Definitions Update Script

2017-05-02 13:15 UTC, danielgrant requested changes
Only a couple of comments around the JSON Schema files from my end.

2017-05-02 13:15 UTC, danielgrant commented on datamodel/APC.json
> +      "default": 1,
Would suggest removing these `default` properties from all the JSON Schema files, they serve no purpose and their meaning can confuse.

2017-05-02 13:15 UTC, danielgrant commented on datamodel/APC.json
> +}
Suggest the JSON Schema files are tightened up through use of `"additionalProperties": false`, preventing additional properties from leaking into requests without being specifically added to the JSON Schema files.

2017-05-02 14:20 UTC, techjacker commented on datamodel/APC.json
> +      "default": 1,
We're using the default id as the database IDs when updating the service.

2017-05-02 14:31 UTC, danielgrant commented on datamodel/APC.json
> +      "default": 1,
I can see now how the `value` fields are being used. I would suggest that we reconsider this approach - embedding values like this in JSON Schema which are then copied into the JSON payload that's sent to the API is not what JSON Schema is designed for.

In addition to this, the files under `examples/...` all include the `value` attribute. If we choose to keep the `value` attribute in the JSON Schema documents as it is now, I would expect these example JSON files to not include the `value` attribute.

2017-05-05 08:31 UTC, danielgrant approved these changes

2017-05-05 08:32 UTC, danielgrant commented
Hi @techjacker, these changes look good. I'm happy for the pull request to be merged.

2017-05-05 10:58 UTC, merged